version: '3.2'
services:
  postgresql-master:
    image: 'postgres:latest'
    restart: always
    container_name: SlaveDB_postgres
    environment:
      - POSTGRES_USER=taqwim
      - POSTGRES_PASSWORD=taqwim
      - POSTGRES_DATABASE=my_database
    volumes:
      - c:\Users\taqwi\DockerTesting\slave_pg\data:/var/lib/postgresql/data
      - c:\Users\taqwi\.ssh\id_rsa:/id_rsa
      - C:\Users\taqwi\.ssh\known_hosts:/known_host
    networks:
      - test_network
networks:
  test_network: 
    name: 'test network'
  

