version: '3.7'

services:
  ssh-local-forward-on-5433:
    image: jnovack/autossh
    container_name: autossh-ssh-local-forward
    environment:
      - SSH_REMOTE_USER=taqwi
      - SSH_REMOTE_HOST=192.168.0.6
      - SSH_REMOTE_PORT=9999
      - SSH_BIND_IP=0.0.0.0
      - SSH_TUNNEL_PORT=5433
      - SSH_TARGET_HOST=localhost
      - SSH_TARGET_PORT=6000
      - SSH_MODE=-L
    volumes:
      - c:\Users\taqwi\.ssh\id_rsa:/id_rsa
      - C:\Users\taqwi\.ssh\known_hosts:/known_host
    expose:
      - 5433
    dns:
      - 8.8.8.8
      - 4.2.2.4
    networks:
      - test_network
networks:
  test_network: 
    name: 'test network'
