version: '3.7'

services:
  ssh-local-forward-on-5433:
    image: jnovack/autossh
    container_name: autossh-ssh-local-forward
    environment:
      - SSH_REMOTE_USER=taqwi
      - SSH_REMOTE_HOST=192.168.0.5
      - SSH_REMOTE_PORT=22
      - SSH_BIND_IP=0.0.0.0
      - SSH_TUNNEL_PORT=5433
      - SSH_TARGET_HOST=localhost
      - SSH_TARGET_PORT=6000
      - SSH_MODE=-L
    restart: always
    volumes:
      - c:\Users\taqwi\DockerTesting\autossh_pg\etc\autossh\id_rsa:/id_rsa
      - c:\Users\taqwi\DockerTesting\autossh_pg\etc\autossh\known_host:/known_host
    dns:
      - 8.8.8.8
      - 4.2.2.4