version: '3.2'
services:
  postgresql-master:
    image: 'postgres:latest'
    restart: always
    container_name: MasterDB_postgres
    ports:
      - "6000:5432"
    expose:
      - 6000
    environment:
      - POSTGRES_USER=taqwim1
      - POSTGRES_PASSWORD=taqwim1
      - POSTGRES_DATABASE=my_database
    volumes:
      - c:\Users\taqwi\DockerTesting\master_pg\my-postgres.conf:/etc/postgresql/postgresql.conf
      - c:\Users\taqwi\DockerTesting\autossh_pg\etc\autossh\id_rsa:/id_rsa
  

