version: '3.2'
services:
  postgresql-master:
    image: 'postgres:latest'
    restart: always
    container_name: MasterDB_postgres
    ports:
      - "6000:5432"
    expose:
      - 6000
    environment:
      - POSTGRES_USER=taqwim1
      - POSTGRES_PASSWORD=taqwim1
      - POSTGRES_DATABASE=my_database
    volumes:
      - c:\Users\taqwi\DockerTesting\master_pg\data:/var/lib/postgresql/data
      - c:\Users\taqwi\.ssh\id_rsa:/id_rsa
      - C:\Users\taqwi\.ssh\known_hosts:/known_host
  

